name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REMOTE_HOST: "13.127.46.165"
  REMOTE_USER: "ubuntu"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ env.REMOTE_HOST }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
      - name: Delete previous running app
        run: ssh ec2 'sudo pm2 stop all && sudo pm2 delete all'
      - name: Delete existing repo
        run: ssh ec2 'rm -rf /home/ubuntu/express/'
      - name: Clone new repo
        run: ssh ec2 'git clone https://github.com/hamza0342/express.git'
      - name: Enter express directory
        run: ssh ec2 'cd /home/ubuntu/express/ && npm install'
      - name: Start app
        run: ssh ec2 'cd /home/ubuntu/express/ && sudo pm2 start app.js'
          
